# Generated by Django 5.2.1 on 2025-06-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='youtube_playlist_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
