# Generated by Django 5.2.1 on 2025-06-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_playlist_youtube_playlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningvideo',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningvideo',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
    ]
