# Generated by Django 4.2.7 on 2025-06-11 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_learningvideo_error_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningvideo',
            options={'ordering': ['-created_at'], 'verbose_name': '学習動画', 'verbose_name_plural': '学習動画'},
        ),
        migrations.AddField(
            model_name='learningvideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningvideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
